apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{- include "nx-cache-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    {{- include "nx-cache-server.selectorLabels" . | nindent 4 }}
