apiVersion: v2
name: nx-cache-server
description: Nx remote cache backed by externally managed S3-compatible storage
type: application
version: 0.1.0
appVersion: "b73a7d8dcf2291deb4922f70417e87a34c14ea97"
kubeVersion: ">=1.25.0-0"
home: https://github.com/dash0hq/nx-cache-server
sources:
  - https://github.com/dash0hq/nx-cache-server
